name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-demo:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-demo:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/devops-demo:latest
            docker stop devops-demo || true
            docker rm devops-demo || true
            docker run -d -p 3000:3000 --name devops-demo ${{ secrets.DOCKER_USERNAME }}/devops-demo:latest
